CREATE TABLE HOTEL(
    ID NUMBER,
    CONSTRAINT HOTEL_PK PRIMARY KEY (ID),
    NAME NVARCHAR2(50) NOT NULL,
    COUNTRY NVARCHAR2(50) NOT NULL,
    CITY NVARCHAR2(50) NOT NULL,
    STREET NVARCHAR2(50) NOT NULL
);